#!/usr/bin/env python3
"""Turn an entity-match bridge CSV into an idempotent MERGE .sql file (AC-1, KTP-695).

The entity-match mode produces a bridge CSV of matched stores. Populating the
BigQuery bridge table `klever_placer_entity_map` used to be hand-written,
ad-hoc SQL — the exact step KTP-695 operationalizes. This generator emits a
self-contained, re-runnable .sql file you can paste into the bq CLI or the
BigQuery web console.

Two properties make it safe:

  * Idempotent — the MERGE is keyed on `klever_location_id` (a store maps to
    exactly one Placer entity), so re-running updates in place and never
    duplicates a row.
  * Bridge-clean — only HIGH-confidence, chain-verified rows are emitted. The
    80% acceptance gate lives upstream in the skill; this is its downstream
    guard so a stray MEDIUM/LOW/UNVERIFIED/UNMATCHED row can never reach the
    bridge through the generated SQL.

Environment (KTP-695 Q2): the default target is DEV. The prod bridge dataset
does not yet exist; once infra confirms the prod project, pass --project to
repoint. The CREATE TABLE IF NOT EXISTS preamble makes a first run on a fresh
environment work without a separate DDL step.

stdlib only. Run: python3 csv_to_merge_sql.py <bridge.csv> --advertiser-id <int> [-o out.sql]
"""

import argparse
import csv
import sys

DEFAULT_PROJECT = "prj-d-grid-insigt-3vm2fcstbw"  # dev (KTP-695 Q2: prod deferred)
DEFAULT_DATASET = "dts_external_data"
DEFAULT_TABLE = "klever_placer_entity_map"

# Bridge columns the MERGE writes. created_at is server-defaulted (omitted).
INSERT_COLUMNS = ["klever_location_id", "placer_entity_id", "advertiser_id", "location_name"]


class NoMatchesError(Exception):
    """Raised when no row survives the HIGH/verified filter — nothing to insert."""


def read_bridge_csv(path):
    """Read a bridge CSV into a list of dict rows (header-keyed)."""
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _sql_str(value):
    """BigQuery string literal: single-quoted, backslash-escaped.

    GoogleSQL does NOT use SQL-standard doubled-quote escaping ('' -> '); a
    doubled quote is parsed as two concatenated literals and errors. Escape the
    backslash first, then the single quote.
    """
    escaped = (value or "").replace("\\", "\\\\").replace("'", "\\'")
    return "'" + escaped + "'"


def _is_bridge_ready(row, min_confidence):
    """A row reaches the bridge only if it is the required confidence, has an
    entity id, and was not flagged chain-unverified."""
    if (row.get("match_confidence") or "").strip().upper() != min_confidence.upper():
        return False
    if not (row.get("placer_entity_id") or "").strip():
        return False
    notes = (row.get("notes") or "").lower()
    if "unverified" in notes or "not in chain" in notes:
        return False
    return True


def generate_merge_sql(rows, advertiser_id, project, dataset=DEFAULT_DATASET,
                       table=DEFAULT_TABLE, min_confidence="HIGH"):
    """Build the CREATE TABLE IF NOT EXISTS + idempotent MERGE SQL string."""
    ready = [r for r in rows if _is_bridge_ready(r, min_confidence)]
    if not ready:
        raise NoMatchesError(
            f"No {min_confidence}-confidence, chain-verified rows to insert. "
            "Nothing was generated."
        )

    fqn = f"`{project}.{dataset}.{table}`"
    adv = int(advertiser_id)

    select_lines = []
    for i, r in enumerate(ready):
        loc = int(str(r["klever_location_id"]).strip())
        entity = _sql_str(r["placer_entity_id"].strip())
        name = _sql_str(r.get("location_name", ""))
        if i == 0:
            select_lines.append(
                f"  SELECT {loc} AS klever_location_id, {entity} AS placer_entity_id, "
                f"{adv} AS advertiser_id, {name} AS location_name"
            )
        else:
            select_lines.append(f"  UNION ALL SELECT {loc}, {entity}, {adv}, {name}")

    using_block = "\n".join(select_lines)
    insert_cols = ", ".join(INSERT_COLUMNS)
    insert_vals = ", ".join(f"S.{c}" for c in INSERT_COLUMNS)

    return f"""\
-- Idempotent bridge-table population for {table}
-- Generated by adtech:placer entity-match (KTP-695). Re-runnable; keyed on klever_location_id.
-- Advertiser: {adv} | HIGH-confidence rows: {len(ready)} | Target: {project} (dev)
-- Prod: the prod bridge dataset does not yet exist (KTP-695 Q2). Repoint --project once infra confirms it.

CREATE TABLE IF NOT EXISTS {fqn} (
  klever_location_id INT64,
  placer_entity_id STRING,
  advertiser_id INT64,
  location_name STRING,
  created_at TIMESTAMP
);

MERGE {fqn} T
USING (
{using_block}
) S
ON T.klever_location_id = S.klever_location_id
WHEN MATCHED THEN UPDATE SET
  placer_entity_id = S.placer_entity_id,
  advertiser_id = S.advertiser_id,
  location_name = S.location_name
WHEN NOT MATCHED THEN INSERT ({insert_cols})
  VALUES ({insert_vals});
"""


def main(argv=None):
    p = argparse.ArgumentParser(
        description="Generate idempotent MERGE SQL for klever_placer_entity_map from a bridge CSV."
    )
    p.add_argument("csv_path", help="entity-match bridge CSV")
    p.add_argument("--advertiser-id", type=int, required=True,
                   help="Klever integer advertiser_id (the bridge needs it; the CSV does not carry it)")
    p.add_argument("--project", default=DEFAULT_PROJECT,
                   help=f"BQ project (default {DEFAULT_PROJECT} = dev; prod deferred per KTP-695 Q2)")
    p.add_argument("--dataset", default=DEFAULT_DATASET)
    p.add_argument("--table", default=DEFAULT_TABLE)
    p.add_argument("--min-confidence", default="HIGH",
                   help="confidence tier required for the bridge (default HIGH)")
    p.add_argument("-o", "--output", help="output .sql path (default: stdout)")
    args = p.parse_args(argv)

    rows = read_bridge_csv(args.csv_path)
    try:
        sql = generate_merge_sql(
            rows, advertiser_id=args.advertiser_id, project=args.project,
            dataset=args.dataset, table=args.table, min_confidence=args.min_confidence,
        )
    except NoMatchesError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(sql)
        print(f"Wrote {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(sql)
    return 0


if __name__ == "__main__":
    sys.exit(main())
